from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session, select
from typing import List

# Import our database session and the Product model we just made
from database import get_session
from models import Product

# Initialize the router
router = APIRouter(
    prefix="/api/products",
    tags=["Products"]
)

@router.get("/", response_model=List[Product])
def get_all_products(session: Session = Depends(get_session)):
    """Fetch all traditional wedding cards from the store."""
    products = session.exec(select(Product)).all()
    return products

@router.get("/{product_id}", response_model=Product)
def get_product(product_id: int, session: Session = Depends(get_session)):
    """Fetch a single wedding card by its ID."""
    product = session.get(Product, product_id)
    if not product:
        raise HTTPException(status_code=404, detail="Card not found")
    return product

@router.post("/", response_model=Product)
def create_product(product: Product, session: Session = Depends(get_session)):
    """Add a new wedding card to the store (Admin only later)."""
    session.add(product)
    session.commit()
    session.refresh(product) # Get the new ID generated by the database
    return product